version: "3.5"

services:
  forpdi-database:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: docker12345
      MYSQL_DATABASE: plataformafor
    networks:
      - default

  forpdi-backend:
    build: ./backend-java
    image: platfor-backend
    volumes:
      - pdfs:/var/forpdi/pdfs
      - arquivos:/var/forpdi/files
    depends_on:
      - forpdi-database
    ports:
      - 8009:8009
      - 8080:8080
    environment:
      - "JAVA_OPTS=-Djava.net.preferIPv4Stack=true"
    networks:
      - default

  forpdi-frontend:
    build: ./frontend-web
    image: platfor-front
    depends_on:
      - forpdi-backend
    environment:
      - VIRTUAL_HOST=for.stg.ufca.edu.br
    networks:
      - proxy
      - default

volumes:
  pdfs:
  arquivos:
  mysql:

networks:
  proxy:
    external:
      name: proxy_nginx_default